### PR TITLE
fix: backwards compatibility for target

### LINKED ISSUE #12: Conditional chaining in resulting js
On the building process of storybook I'm having this error

```
ERROR in ./node_modules/base-analysis/lib-esm/util/autoPeakPicking.js 12:45
Module parse failed: Unexpected token (12:45)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export function autoPeakPicking(measurement, options = {}) {
|     const { xVariable = 'x', yVariable = 'y', normalizationOptions, minPeakWidth, gsdOptions = {}, } = options;
>     let x = measurement.variables[xVariable]?.data;
|     let y = measurement.variables[yVariable]?.data;
|     if (!x || !y)
```

I understand that the conditional chaining is not supported, should we build this package in a lower level or is it better to support this from the storybook webpack? @targos @lpatiny

### PR DESCRIPTION
**Pull request by maasencioh**
closes #12

### CODE REVIEW

**Comment by targos** [comment]
I'm -1 on doing fixes that cannot be verified by the github actions CI

**Comment by maasencioh** [comment]
@targos what do you propose for this? the actual broken error is not in this repo, and because it's breaking on the only storybook process I don't know how to add a test for this change

**Comment by targos** [comment]
On this issue my stance is that the problem is with storybook, and so it should not be fixed in this repo

**Comment by targos** [comment]
Fixed in https://github.com/zakodium/react-plot/pull/275

**Pull request closed without merging**
